# -*- coding: utf-8 -*-
"""Naive_Bayes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19h-P160hFzdUqqaAxhl4SnVSoTwlpiPk

#Cover Page

**Developed by:**

**Mohamed Fathi - 41810059**

**Ahmed Saber - 41810077**

#Import the dataset from drive
"""

!gdown --id 1MbUWPsEZJ_Dana5RC07wUGTIgzN92Uld

"""#Importing libraries"""

from sklearn.naive_bayes import GaussianNB 
import pandas as pd
import seaborn as sns
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

"""# show how the data looks like"""

data = pd.read_csv('seeds.csv')
df.head()

"""#Normalization"""

df = data.drop('Type', axis=1)
df_norm = (df-df.min())/(df.max()-df.min())
df_norm = pd.concat((df_norm, data.Type), 1)
df_norm.head()

"""#Start Split the data and train"""

X_train, X_test, y_train, y_test = train_test_split(df_norm.drop('Type', axis=1), df_norm['Type'], test_size = 0.20)
print(len(X_train), "train +", len(X_test), "valid")

"""#Using Naive_Bayes for trainning """

classifier = GaussianNB()
classifier =classifier.fit(X_train, y_train)
y_pred  =  classifier.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
cm

sns.heatmap(cm, annot=True)
plt.xlabel('Prediction')
plt.ylabel('Truth')

"""# Accurcy"""

var="%"
print("Accuracy: %0.1f" % (classifier.score(X_test,y_test)*100), var[0])

"""#find the mean square error"""

lin_mse = mean_squared_error(y_test, y_pred)
lin_rmse = np.sqrt(lin_mse)
lin_rmse

lin_mae = mean_absolute_error(y_test, y_pred)
lin_mae